
Lmod is automatically replacing "nvhpc/23.9" with "gcc-native/12.3".


Lmod is automatically replacing "PrgEnv-nvhpc/8.5.0" with "PrgEnv-gnu/8.5.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.28

environment: line 5: __conda_exe: command not found

Currently Loaded Modules:
  1) libfabric/1.15.2.0       10) cray-pmi/6.1.13
  2) craype-network-ofi       11) cray-pals/1.3.4
  3) perftools-base/23.12.0   12) cray-libpals/1.3.4
  4) darshan/3.4.4            13) craype-x86-milan
  5) xalt/3.0.2-202408282050  14) PrgEnv-gnu/8.5.0
  6) gcc-native/12.3          15) cray-hdf5-parallel/1.12.2.9
  7) craype/2.7.30            16) cudnn/9.1.0
  8) cray-dsmml/0.2.2         17) conda/2024-04-29
  9) cray-mpich/8.1.28

 

Traceback (most recent call last):
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/test_ensemble_launcher.py", line 14, in <module>
    el = ensemble_launcher(f"config_{args.ntasks}.json")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/../../ensemble_launcher.py", line 301, in __init__
    self.read_input_file()
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/../../ensemble_launcher.py", line 322, in read_input_file
    self.logfile = data.get("logfile",self.logfile)
                                      ^^^^^^^^^^^^
AttributeError: 'ensemble_launcher' object has no attribute 'logfile'

Lmod is automatically replacing "nvhpc/23.9" with "gcc-native/12.3".


Lmod is automatically replacing "PrgEnv-nvhpc/8.5.0" with "PrgEnv-gnu/8.5.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.28

environment: line 5: __conda_exe: command not found

Currently Loaded Modules:
  1) libfabric/1.15.2.0       10) cray-pmi/6.1.13
  2) craype-network-ofi       11) cray-pals/1.3.4
  3) perftools-base/23.12.0   12) cray-libpals/1.3.4
  4) darshan/3.4.4            13) craype-x86-milan
  5) xalt/3.0.2-202408282050  14) PrgEnv-gnu/8.5.0
  6) gcc-native/12.3          15) cray-hdf5-parallel/1.12.2.9
  7) craype/2.7.30            16) cudnn/9.1.0
  8) cray-dsmml/0.2.2         17) conda/2024-04-29
  9) cray-mpich/8.1.28

 

Traceback (most recent call last):
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/test_ensemble_launcher.py", line 17, in <module>
    total_poll_time = el.run_tasks()
                      ^^^^^^^^^^^^^^
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/../../ensemble_launcher.py", line 572, in run_tasks
    self.run_tasks_serial()
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/../../ensemble_launcher.py", line 540, in run_tasks_serial
    launched_tasks = self.launch_ready_tasks(ensemble,local_pid=local_pid,my_pid=my_pid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/../../ensemble_launcher.py", line 471, in launch_ready_tasks
    p = self.launch_task(task_id,ensemble)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/datascience/hari/ensemble_launcher/tests/effect_of_ntasks/../../ensemble_launcher.py", line 435, in launch_task
    p = subprocess.Popen(task_info["cmd"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/soft/applications/conda/2024-04-29/mconda3/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/soft/applications/conda/2024-04-29/mconda3/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable
